site_name: cmda
site_decription: Analysis package

theme:
  name: material
  custom_dir: 'custom_theme/'


plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - CMDA: index.md
  - Tutorial:
    - Feature Extraction: tutorials/feature_extraction.md
    - Feature Object: tutorials/feature_object.ipynb
  - Built-in Features:
    - Time-Domain Featrues: features/time_domain.md
    - Frequency-Domain Features: features/frequency_domain.md